#!/usr/bin/env python3
import docker
import os
import time
import sys
import threading
# from guesslang import Guess
from flask import Flask, render_template, request
from flask_basicauth import BasicAuth
app = Flask(__name__, template_folder='views',static_folder='')

host = os.environ.get('ip', '0.0.0.0')
port= os.environ.get('port', '8080')
filename = sys.argv[1]
file_path = os.path.dirname(os.path.realpath(__file__))

data={}
data['title'] = "Editing " + filename
data['mode'] = os.environ.get('mode', 'toml')

if 'user' in os.environ:
    app.config['BASIC_AUTH_USERNAME'] = os.environ.get('user')
    app.config['BASIC_AUTH_PASSWORD'] = os.environ.get('pass')
    app.config['BASIC_AUTH_FORCE'] = True

basic_auth = BasicAuth(app)

@app.route('/')
def main():
    with open(filename, 'r') as file:
        data['data'] = file.read()
    return render_template('edit.html', data=data)

@app.route('/edit', methods=['POST'])
def edit():
    new = request.form['new']
    with open(filename, 'w') as file:
        file.write(new)
    if 'CC' in os.environ:
        threading.Thread(name='restart_docker', target=restart_docker).start()
    return f'Worked'

def restart_docker():
    time.sleep(3)
    docker_client = docker.DockerClient(base_url='unix://var/run/docker.sock')
    docker_client.containers.get(os.environ["CC"]).restart()

if __name__ == '__main__':
    app.run(host=host, port=port)
